version: '3.7'

services:
  mailserver:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: yourdomain.noip.com
    container_name: mailserver
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_POSTGREY=1
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=manual
    volumes:
      - ./config/:/tmp/docker-mailserver/
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    env_file:
      - .env
    restart: always

  roundcube:
    image: roundcube/roundcubemail
    container_name: roundcube
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=dovecot
      - ROUNDCUBEMAIL_SMTP_SERVER=postfix
    volumes:
      - ./roundcube/config:/var/www/html/config
      - ./roundcube/plugins:/var/www/html/plugins
      - ./roundcube/skins:/var/www/html/skins
    ports:
      - "8080:80"
    depends_on:
      - mailserver

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/webmail.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - roundcube
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"
    restart: always
